workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      vars:
        XCODE_WORKSPACE: "ios/meetgo.xcworkspace"
        XCODE_SCHEME: "meetgo"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install && cd ..
      - name: Build iOS app
        script: |
          xcodebuild \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -configuration Release \
          -sdk iphoneos \
          -archivePath build/meetgo.xcarchive archive

          xcodebuild \
          -exportArchive \
          -archivePath build/meetgo.xcarchive \
          -exportOptionsPlist ios/exportOptions.plist \
          -exportPath build/ios
    artifacts:
      - build/ios/*.ipa
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN