workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      vars:
        XCODE_WORKSPACE: "ios/meetgo.xcworkspace"
        XCODE_SCHEME: "meetgo"
      xcode: latest
      cocoapods: default
    scripts:
      - echo "Installing dependencies"
      - npm install
      - cd ios && pod install && cd ..
      - echo "Building iOS app"
      - |
        xcodebuild \
        -workspace "$XCODE_WORKSPACE" \
        -scheme "$XCODE_SCHEME" \
        -configuration Release \
        -sdk iphoneos \
        -derivedDataPath build
    artifacts:
      - build/**/*.app
      - build/**/*.ipa
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        ios:
          app_id: "1:1073852357664:ios:7f27e4ea8fd25ceb5eb045"
          groups: "Tester"
          release_notes: "New iOS build uploaded from Codemagic"
